services:
  backend:
    build: back/
    container_name: projo-backend
    ports:
      - "3000:3000"
    env_file:
      - back/.env
    restart: unless-stopped

  frontend:
    build: frontend/
    container_name: projo-frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env.prod
    depends_on:
      - backend
    restart: unless-stopped

